port:  5000
encoding: utf-8

collections:
  projects:
    output: true
    permalink: /:collection/:path/

defaults:
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
